# Generated by Django 6.0.3 on 2026-03-31 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='Aforo de invitados'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='join_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='GuestAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bookings.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia de Invitado',
                'verbose_name_plural': 'Asistencias de Invitados',
                'unique_together': {('reservation', 'user')},
            },
        ),
    ]
